### PR TITLE
More of a question than a Pull Request:

### PR DESCRIPTION
**Pull request by thirtytwobits**
Shouldn't the transitivityLaw be something more like this? For other laws you just pass in the terms and the rule is generated. For this one you had to form part of the rule as an argument yourself. Not sure I'm getting this yet. Please criticise.

### CODE REVIEW

**Comment by rebcabin** [comment]
You have definitely found a problem, and I think both of our solutions are wrong : )

I didn't discover the problem myself because I actually haven't USED transitivity in any proofs. I would have broken it :)

Here, briefly, is the problem, with a solution sketch that I need to work on and test. The problem is that we need a way to introduce transitivity WITHOUT using stuff we haven't defined or proved, yet. My solution is wrong because I sneaked in `and`, which hasn't been defined. Your solution is wrong because it blatantly uses `If`, a built-in we haven't begun to talk about, and `False`, a built-in we're explicitly disallowing!

**Comment by rebcabin** [comment]
Ok, here is a potential solution. I will criticize this solution after giving a couple of philosophical comments:

```
   transitivityLaw[sameq[x_, y_], sameq[y_, z_]] := sameq[x, z]
```

PHILOSOPHY:
We can't use `and` because it's not been defined. But there is a much deeper reason we must not use ANYTHING except pattern matching: no `ifs`, `ands`, or `buts` (excuse the pun).

At this stage of development, we are writing a SEQUENCE of axioms and theorems, each depending ONLY on the ones before it in the sequence. We are using ONLY pattern matching, the particular forms of it allowed by mathics, to recognize terms that we can rewrite. Pattern-matching, as we're allowing it, can use built-ins on the conditional side of the patterns, as in 

```
leibnizPick1[part_] =
    expr:eqv[args___] /; MemberQ[expr, true] :> {args}[[part]]
```

where `/;` is `Condition`, and the expression, with all syntax expanded, is

```
RuleDelayed[
  Condition[
    Pattern[expr, eqv[
      Pattern[args, BlankNullSequence[]]]], 
    MemberQ[expr, true]], 
  Part[List[args], part]]
```

The reason (meta-reason?) we don't allow built-ins on the right-hand side of any rule is that we are writing rules that represent our (human) reasoning about the manipulation of inert symbols. We're building up logic by just syntactic rules. If we allowed the testing of things at run time, the way you would do with your use of built-in `If`, we wouldn't just be rewriting symbols, we would be testing them, dipping into MEANING before we even have any idea what MEANING might MEAN! 

My bad solution using `and` is kind of a halfway dip into "meaning." I was trying to express the idea that TWO patterns must match before `transitivity` can fire, and I inadvertently expressed that idea using `and`, but that use is AT THE WRONG LEVEL. I should express the idea that pattern_1 (`sameq[x_,y_]`) AND pattern_2 (`sameq[y_,z_]`) must match, and express that idea at the level of the pattern, NOT INSIDE the pattern. 

You see how nicely this critique is evolving? We make a fuzzy philosophical critique like "at the wrong level" into a syntactic issue: I can't say `and` inside the pattern because that's the wrong level; I have to say it OUTSIDE the pattern, and we only have one way to do that, and it's with extra arguments (curried or not --- that's something I haven't figured out yet). 

So my use of the symbol `and` isn't only wrong because we haven't defined `and` yet, it's also a level-mistake. 

Your use of `If` to affect the outcome is using tools we're not allowed to use (yet), but is also at the wrong level. You purport to return `False` if the conditions of transitivity are not met. But that's not a correct definition of transitivity. Transitivity isn't `True` or `False` (unless we lift the entire project into some higher-level Maybe monad, but I digress unhelpfully). Transitivity either pertains or it doesn't, and our only tool for testing pertinence is pattern matching. If transitivity pertains, we get to rewrite a pair of patterns as a certain outcome. If transitivity doesn't pertain, then we don't get to rewrite the pair of patterns as anything, let alone as `False`.

Built-ins in the `Condition` part of a pattern aren't supposed to do any rewriting (I suppose one could do some awful side-effectful hackery, but then I would just disallow it). Those `Conditions` just test whether some pattern pertains, they can't affect the outcome. 

I need to think a lot more about this, but I'm pretty sure I'm on the correct road, here, and your issue is a GREAT CATCH, and exposed some carelessness on my part. Keep it up!

**Comment by rebcabin** [comment]
Here is another point: we actually need `transitivity` itself to be commutative. The philosophical meta-AND, represented by the comma above the line, that connects the two premises of transitivity is commutative. 

```
    x === y,    y === z    <~~~ the "comma" on this line is a commutative meta-AND
    ------------------
          x === z
```

which means we need either two rule overloads:

```
transitivityLaw[sameq[x_, y_], sameq[y_, z_]] := sameq[x, z]
transitivityLaw[sameq[y_, z_], sameq[x_, y_]] := sameq[x, z]
```

or use the `Orderless` attribute

```
SetAttributes[transitivity, Orderless]
transitivityLaw[sameq[x_, y_], sameq[y_, z_]] := sameq[x, z]
```

**Comment by thirtytwobits** [comment]
Is commutativity introduced before transitivity? If so then shouldn't you use that? If not then we can't define transitivity, right?

**Comment by rebcabin** [comment]
You could certainly use commutativity of `sameq` expressions in your proofs to avoid having two rules for transitivity of `sameq` expressions. The commutativity I was referring to was at a different level: commutativity of the implied meta-`AND`, represented by a comma, in the meta-language that defines transitivity. G&S don't explicitly talk about this meta language, i.e., they don't go meta-meta-, but they use the meta-language every time they write out one of those horizontal-bar inference rules. This meta language can be formalized, itself, of course. I think the name for the meta language is the `sequent calculus`. 

I think it's important to keep this level-hopping straight in our heads as we go through this stuff. I'm going to make another pass over all my documents to work on clarifying this issue. The key will be crystal clarity about whether we're talking about something, in which case we're using a meta-language to talk about the thing, or using something, in which case we're not using a meta-language, and we're operating at a level called the "object level." 

Mathics (and Mathematica) let us use the same language at both the meta level and at the object level, leading to ambiguity. That's why I'm going to make a clarifying pass.

At this rate, getting through G&S is turning into a multi-year project :)

**Pull request closed without merging**
